__author__ = 'Bene'

from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.image import Image
from kivy.uix.button import Button


class Game(App):
    def build(self):


        layout = BoxLayout(orientation='horizontal')
        layout.add_widget(Image(source='Weiss.jpg'))
        layout.add_widget(Image(source='Numbers/1.jpg'))
        layout.add_widget(Image(source='Numbers/2.jpg'))
        layout.add_widget(Image(source='Numbers/3.jpg'))
        layout.add_widget(Image(source='Numbers/4.jpg'))
        layout.add_widget(Image(source='Numbers/5.jpg'))
        layout.add_widget(Image(source='Numbers/6.jpg'))
        layout.add_widget(Image(source='Numbers/7.jpg'))
        layout.add_widget(Image(source='Numbers/8.jpg'))
        layout.add_widget(Image(source='Numbers/9.jpg'))
        layout.add_widget(Image(source='Numbers/10.jpg'))
        layout.add_widget(Image(source='Numbers/11.jpg'))
        layout.add_widget(Image(source='Numbers/12.jpg'))
        layout.add_widget(Image(source='Numbers/13.jpg'))

        layout1 = BoxLayout(orientation='horizontal')
        layout1.add_widget(Image(source='Letters/A.jpg'))
        layout1.add_widget(Button(background_normal='Wasser.jpg'))
        layout1.add_widget(Button(background_normal='Wasser.jpg'))
        layout1.add_widget(Button(background_normal='Wasser.jpg'))
        layout1.add_widget(Button(background_normal='Wasser.jpg'))
        layout1.add_widget(Button(background_normal='Wasser.jpg'))
        layout1.add_widget(Button(background_normal='Wasser.jpg'))
        layout1.add_widget(Button(background_normal='Wasser.jpg'))
        layout1.add_widget(Button(background_normal='Wasser.jpg'))
        layout1.add_widget(Button(background_normal='Wasser.jpg'))
        layout1.add_widget(Button(background_normal='Wasser.jpg'))
        layout1.add_widget(Button(background_normal='Wasser.jpg'))
        layout1.add_widget(Button(background_normal='Wasser.jpg'))
        layout1.add_widget(Button(background_normal='Wasser.jpg'))

        layout2 = BoxLayout(orientation='horizontal')
        layout2.add_widget(Image(source='Letters/B.jpg'))
        layout2.add_widget(Button(background_normal='Wasser.jpg'))
        layout2.add_widget(Button(background_normal='Wasser.jpg'))
        layout2.add_widget(Button(background_normal='Wasser.jpg'))
        layout2.add_widget(Button(background_normal='Wasser.jpg'))
        layout2.add_widget(Button(background_normal='Wasser.jpg'))
        layout2.add_widget(Button(background_normal='Wasser.jpg'))
        layout2.add_widget(Button(background_normal='Wasser.jpg'))
        layout2.add_widget(Button(background_normal='Wasser.jpg'))
        layout2.add_widget(Button(background_normal='Wasser.jpg'))
        layout2.add_widget(Button(background_normal='Wasser.jpg'))
        layout2.add_widget(Button(background_normal='Wasser.jpg'))
        layout2.add_widget(Button(background_normal='Wasser.jpg'))
        layout2.add_widget(Button(background_normal='Wasser.jpg'))

        layout3 = BoxLayout(orientation='horizontal')
        layout3.add_widget(Image(source='Letters/C.jpg'))
        layout3.add_widget(Button(background_normal='Wasser.jpg'))
        layout3.add_widget(Button(background_normal='Wasser.jpg'))
        layout3.add_widget(Button(background_normal='Wasser.jpg'))
        layout3.add_widget(Button(background_normal='Wasser.jpg'))
        layout3.add_widget(Button(background_normal='Wasser.jpg'))
        layout3.add_widget(Button(background_normal='Wasser.jpg'))
        layout3.add_widget(Button(background_normal='Wasser.jpg'))
        layout3.add_widget(Button(background_normal='Wasser.jpg'))
        layout3.add_widget(Button(background_normal='Wasser.jpg'))
        layout3.add_widget(Button(background_normal='Wasser.jpg'))
        layout3.add_widget(Button(background_normal='Wasser.jpg'))
        layout3.add_widget(Button(background_normal='Wasser.jpg'))
        layout3.add_widget(Button(background_normal='Wasser.jpg'))

        layout4 = BoxLayout(orientation='horizontal')
        layout4.add_widget(Image(source='Letters/D.jpg'))
        layout4.add_widget(Button(background_normal='Wasser.jpg'))
        layout4.add_widget(Button(background_normal='Wasser.jpg'))
        layout4.add_widget(Button(background_normal='Wasser.jpg'))
        layout4.add_widget(Button(background_normal='Wasser.jpg'))
        layout4.add_widget(Button(background_normal='Wasser.jpg'))
        layout4.add_widget(Button(background_normal='Wasser.jpg'))
        layout4.add_widget(Button(background_normal='Wasser.jpg'))
        layout4.add_widget(Button(background_normal='Wasser.jpg'))
        layout4.add_widget(Button(background_normal='Wasser.jpg'))
        layout4.add_widget(Button(background_normal='Wasser.jpg'))
        layout4.add_widget(Button(background_normal='Wasser.jpg'))
        layout4.add_widget(Button(background_normal='Wasser.jpg'))
        layout4.add_widget(Button(background_normal='Wasser.jpg'))

        layout5 = BoxLayout(orientation='horizontal')
        layout5.add_widget(Image(source='Letters/E.jpg'))
        layout5.add_widget(Button(background_normal='Wasser.jpg'))
        layout5.add_widget(Button(background_normal='Wasser.jpg'))
        layout5.add_widget(Button(background_normal='Wasser.jpg'))
        layout5.add_widget(Button(background_normal='Wasser.jpg'))
        layout5.add_widget(Button(background_normal='Wasser.jpg'))
        layout5.add_widget(Button(background_normal='Wasser.jpg'))
        layout5.add_widget(Button(background_normal='Wasser.jpg'))
        layout5.add_widget(Button(background_normal='Wasser.jpg'))
        layout5.add_widget(Button(background_normal='Wasser.jpg'))
        layout5.add_widget(Button(background_normal='Wasser.jpg'))
        layout5.add_widget(Button(background_normal='Wasser.jpg'))
        layout5.add_widget(Button(background_normal='Wasser.jpg'))
        layout5.add_widget(Button(background_normal='Wasser.jpg'))

        layout6 = BoxLayout(orientation='horizontal')
        layout6.add_widget(Image(source='Letters/F.jpg'))
        layout6.add_widget(Button(background_normal='Wasser.jpg'))
        layout6.add_widget(Button(background_normal='Wasser.jpg'))
        layout6.add_widget(Button(background_normal='Wasser.jpg'))
        layout6.add_widget(Button(background_normal='Wasser.jpg'))
        layout6.add_widget(Button(background_normal='Wasser.jpg'))
        layout6.add_widget(Button(background_normal='Wasser.jpg'))
        layout6.add_widget(Button(background_normal='Wasser.jpg'))
        layout6.add_widget(Button(background_normal='Wasser.jpg'))
        layout6.add_widget(Button(background_normal='Wasser.jpg'))
        layout6.add_widget(Button(background_normal='Wasser.jpg'))
        layout6.add_widget(Button(background_normal='Wasser.jpg'))
        layout6.add_widget(Button(background_normal='Wasser.jpg'))
        layout6.add_widget(Button(background_normal='Wasser.jpg'))

        layout7 = BoxLayout(orientation='horizontal')
        layout7.add_widget(Image(source='Letters/G.jpg'))
        layout7.add_widget(Button(background_normal='Wasser.jpg'))
        layout7.add_widget(Button(background_normal='Wasser.jpg'))
        layout7.add_widget(Button(background_normal='Wasser.jpg'))
        layout7.add_widget(Button(background_normal='Wasser.jpg'))
        layout7.add_widget(Button(background_normal='Wasser.jpg'))
        layout7.add_widget(Button(background_normal='Wasser.jpg'))
        layout7.add_widget(Button(background_normal='Wasser.jpg'))
        layout7.add_widget(Button(background_normal='Wasser.jpg'))
        layout7.add_widget(Button(background_normal='Wasser.jpg'))
        layout7.add_widget(Button(background_normal='Wasser.jpg'))
        layout7.add_widget(Button(background_normal='Wasser.jpg'))
        layout7.add_widget(Button(background_normal='Wasser.jpg'))
        layout7.add_widget(Button(background_normal='Wasser.jpg'))

        layout8 = BoxLayout(orientation='horizontal')
        layout8.add_widget(Image(source='Letters/H.jpg'))
        layout8.add_widget(Button(background_normal='Wasser.jpg'))
        layout8.add_widget(Button(background_normal='Wasser.jpg'))
        layout8.add_widget(Button(background_normal='Wasser.jpg'))
        layout8.add_widget(Button(background_normal='Wasser.jpg'))
        layout8.add_widget(Button(background_normal='Wasser.jpg'))
        layout8.add_widget(Button(background_normal='Wasser.jpg'))
        layout8.add_widget(Button(background_normal='Wasser.jpg'))
        layout8.add_widget(Button(background_normal='Wasser.jpg'))
        layout8.add_widget(Button(background_normal='Wasser.jpg'))
        layout8.add_widget(Button(background_normal='Wasser.jpg'))
        layout8.add_widget(Button(background_normal='Wasser.jpg'))
        layout8.add_widget(Button(background_normal='Wasser.jpg'))
        layout8.add_widget(Button(background_normal='Wasser.jpg'))

        layout9 = BoxLayout(orientation='horizontal')
        layout9.add_widget(Image(source='Letters/I.jpg'))
        layout9.add_widget(Button(background_normal='Wasser.jpg'))
        layout9.add_widget(Button(background_normal='Wasser.jpg'))
        layout9.add_widget(Button(background_normal='Wasser.jpg'))
        layout9.add_widget(Button(background_normal='Wasser.jpg'))
        layout9.add_widget(Button(background_normal='Wasser.jpg'))
        layout9.add_widget(Button(background_normal='Wasser.jpg'))
        layout9.add_widget(Button(background_normal='Wasser.jpg'))
        layout9.add_widget(Button(background_normal='Wasser.jpg'))
        layout9.add_widget(Button(background_normal='Wasser.jpg'))
        layout9.add_widget(Button(background_normal='Wasser.jpg'))
        layout9.add_widget(Button(background_normal='Wasser.jpg'))
        layout9.add_widget(Button(background_normal='Wasser.jpg'))
        layout9.add_widget(Button(background_normal='Wasser.jpg'))

        layout10 = BoxLayout(orientation='horizontal')
        layout10.add_widget(Image(source='Letters/J.jpg'))
        layout10.add_widget(Button(background_normal='Wasser.jpg'))
        layout10.add_widget(Button(background_normal='Wasser.jpg'))
        layout10.add_widget(Button(background_normal='Wasser.jpg'))
        layout10.add_widget(Button(background_normal='Wasser.jpg'))
        layout10.add_widget(Button(background_normal='Wasser.jpg'))
        layout10.add_widget(Button(background_normal='Wasser.jpg'))
        layout10.add_widget(Button(background_normal='Wasser.jpg'))
        layout10.add_widget(Button(background_normal='Wasser.jpg'))
        layout10.add_widget(Button(background_normal='Wasser.jpg'))
        layout10.add_widget(Button(background_normal='Wasser.jpg'))
        layout10.add_widget(Button(background_normal='Wasser.jpg'))
        layout10.add_widget(Button(background_normal='Wasser.jpg'))
        layout10.add_widget(Button(background_normal='Wasser.jpg'))

        layout11 = BoxLayout(orientation='horizontal')
        layout11.add_widget(Image(source='Letters/K.jpg'))
        layout11.add_widget(Button(background_normal='Wasser.jpg'))
        layout11.add_widget(Button(background_normal='Wasser.jpg'))
        layout11.add_widget(Button(background_normal='Wasser.jpg'))
        layout11.add_widget(Button(background_normal='Wasser.jpg'))
        layout11.add_widget(Button(background_normal='Wasser.jpg'))
        layout11.add_widget(Button(background_normal='Wasser.jpg'))
        layout11.add_widget(Button(background_normal='Wasser.jpg'))
        layout11.add_widget(Button(background_normal='Wasser.jpg'))
        layout11.add_widget(Button(background_normal='Wasser.jpg'))
        layout11.add_widget(Button(background_normal='Wasser.jpg'))
        layout11.add_widget(Button(background_normal='Wasser.jpg'))
        layout11.add_widget(Button(background_normal='Wasser.jpg'))
        layout11.add_widget(Button(background_normal='Wasser.jpg'))

        layout12 = BoxLayout(orientation='horizontal')
        layout12.add_widget(Image(source='Letters/L.jpg'))
        layout12.add_widget(Button(background_normal='Wasser.jpg'))
        layout12.add_widget(Button(background_normal='Wasser.jpg'))
        layout12.add_widget(Button(background_normal='Wasser.jpg'))
        layout12.add_widget(Button(background_normal='Wasser.jpg'))
        layout12.add_widget(Button(background_normal='Wasser.jpg'))
        layout12.add_widget(Button(background_normal='Wasser.jpg'))
        layout12.add_widget(Button(background_normal='Wasser.jpg'))
        layout12.add_widget(Button(background_normal='Wasser.jpg'))
        layout12.add_widget(Button(background_normal='Wasser.jpg'))
        layout12.add_widget(Button(background_normal='Wasser.jpg'))
        layout12.add_widget(Button(background_normal='Wasser.jpg'))
        layout12.add_widget(Button(background_normal='Wasser.jpg'))
        layout12.add_widget(Button(background_normal='Wasser.jpg'))

        layout13 = BoxLayout(orientation='horizontal')
        layout13.add_widget(Image(source='Letters/M.jpg'))
        layout13.add_widget(Button(background_normal='Wasser.jpg'))
        layout13.add_widget(Button(background_normal='Wasser.jpg'))
        layout13.add_widget(Button(background_normal='Wasser.jpg'))
        layout13.add_widget(Button(background_normal='Wasser.jpg'))
        layout13.add_widget(Button(background_normal='Wasser.jpg'))
        layout13.add_widget(Button(background_normal='Wasser.jpg'))
        layout13.add_widget(Button(background_normal='Wasser.jpg'))
        layout13.add_widget(Button(background_normal='Wasser.jpg'))
        layout13.add_widget(Button(background_normal='Wasser.jpg'))
        layout13.add_widget(Button(background_normal='Wasser.jpg'))
        layout13.add_widget(Button(background_normal='Wasser.jpg'))
        layout13.add_widget(Button(background_normal='Wasser.jpg'))
        layout13.add_widget(Button(background_normal='Wasser.jpg'))

        layoutMain = BoxLayout(orientation='vertical')
        layoutMain.add_widget(layout)
        layoutMain.add_widget(layout1)
        layoutMain.add_widget(layout2)
        layoutMain.add_widget(layout3)
        layoutMain.add_widget(layout4)
        layoutMain.add_widget(layout5)
        layoutMain.add_widget(layout6)
        layoutMain.add_widget(layout7)
        layoutMain.add_widget(layout8)
        layoutMain.add_widget(layout9)
        layoutMain.add_widget(layout10)
        layoutMain.add_widget(layout11)
        layoutMain.add_widget(layout12)
        layoutMain.add_widget(layout13)
        return layoutMain


if __name__ == '__main__':
    Game().run()