__author__ = 'Bene'

from kivy.app import App
from kivy.uix.gridlayout import GridLayout
from kivy.uix.image import Image
from kivy.core.window import Window
from kivy.uix.button import Button
from kivy.uix.widget import Widget


class Pitch(App):

        def build(self):

                h = Window.height
                w = Window.width

                if h < w:
                            s = h
                            layout = GridLayout(cols=11, rows=11)
                            GridLayout.height = s
                            GridLayout.width = s

                else:
                            s = w
                            layout = GridLayout(cols=11, rows=11)
                            GridLayout.height = s
                            GridLayout.width = s

                Wsr1 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr2 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr3 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr4 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr5 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr6 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr7 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr8 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr9 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr10 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr11 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr12 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr13 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr14 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr15 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr16 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr17 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr18 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr19 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr20 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr21 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr22 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr23 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr24 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr25 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr26 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr27 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr28 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr29 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr30 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr31 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr32 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr33 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr34 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr35 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr36 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr37 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr38 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr39 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr40 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr41 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr42 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr43 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr44 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr45 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr46 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr47 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr48 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr49 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr50 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr51 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr52 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr53 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr54 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr55 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr56 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr57 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr58 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr59 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr60 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr61 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr62 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr63 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr64 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr65 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr66 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr67 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr68 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr69 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr70 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr71 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr72 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr73 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr74 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr75 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr76 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr77 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr78 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr79 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr80 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr81 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr82 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr83 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr84 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr85 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr86 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr87 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr88 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr89 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr90 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr91 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr92 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr93 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr94 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr95 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr96 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr97 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr98 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr99 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')
                Wsr100 = Button(background_normal='Wasser.jpg', background_down='Schiff.jpg', background_disabled_normal='Schiff.jpg')


                layout.add_widget(Image(source='Weiss.png'))
                layout.add_widget(Button(background_normal='Numbers/1.jpg', background_down='Numbers/1C.jpg'))
                layout.add_widget(Button(background_normal='Numbers/2.jpg', background_down='Numbers/2C.jpg'))
                layout.add_widget(Button(background_normal='Numbers/3.jpg', background_down='Numbers/3C.jpg'))
                layout.add_widget(Button(background_normal='Numbers/4.jpg', background_down='Numbers/4C.jpg'))
                layout.add_widget(Button(background_normal='Numbers/5.jpg', background_down='Numbers/5C.jpg'))
                layout.add_widget(Button(background_normal='Numbers/6.jpg', background_down='Numbers/6C.jpg'))
                layout.add_widget(Button(background_normal='Numbers/7.jpg', background_down='Numbers/7C.jpg'))
                layout.add_widget(Button(background_normal='Numbers/8.jpg', background_down='Numbers/8C.jpg'))
                layout.add_widget(Button(background_normal='Numbers/9.jpg', background_down='Numbers/9C.jpg'))
                layout.add_widget(Button(background_normal='Numbers/10.jpg', background_down='Numbers/10C.jpg'))
                layout.add_widget(Button(background_normal='Letters/A.jpg', background_down='Letters/AC.jpg'))
                layout.add_widget(Wsr1)
                layout.add_widget(Wsr2)
                layout.add_widget(Wsr3)
                layout.add_widget(Wsr4)
                layout.add_widget(Wsr5)
                layout.add_widget(Wsr6)
                layout.add_widget(Wsr7)
                layout.add_widget(Wsr8)
                layout.add_widget(Wsr9)
                layout.add_widget(Wsr10)
                layout.add_widget(Button(background_normal='Letters/B.jpg', background_down='Letters/BC.jpg'))
                layout.add_widget(Wsr11)
                layout.add_widget(Wsr12)
                layout.add_widget(Wsr13)
                layout.add_widget(Wsr14)
                layout.add_widget(Wsr15)
                layout.add_widget(Wsr16)
                layout.add_widget(Wsr17)
                layout.add_widget(Wsr18)
                layout.add_widget(Wsr19)
                layout.add_widget(Wsr20)
                layout.add_widget(Button(background_normal='Letters/C.jpg', background_down='Letters/CC.jpg'))
                layout.add_widget(Wsr21)
                layout.add_widget(Wsr22)
                layout.add_widget(Wsr23)
                layout.add_widget(Wsr24)
                layout.add_widget(Wsr25)
                layout.add_widget(Wsr26)
                layout.add_widget(Wsr27)
                layout.add_widget(Wsr28)
                layout.add_widget(Wsr29)
                layout.add_widget(Wsr30)
                layout.add_widget(Button(background_normal='Letters/D.jpg', background_down='Letters/DC.jpg'))
                layout.add_widget(Wsr31)
                layout.add_widget(Wsr32)
                layout.add_widget(Wsr33)
                layout.add_widget(Wsr34)
                layout.add_widget(Wsr35)
                layout.add_widget(Wsr36)
                layout.add_widget(Wsr37)
                layout.add_widget(Wsr38)
                layout.add_widget(Wsr39)
                layout.add_widget(Wsr40)
                layout.add_widget(Button(background_normal='Letters/E.jpg', background_down='Letters/EC.jpg'))
                layout.add_widget(Wsr41)
                layout.add_widget(Wsr42)
                layout.add_widget(Wsr43)
                layout.add_widget(Wsr44)
                layout.add_widget(Wsr45)
                layout.add_widget(Wsr46)
                layout.add_widget(Wsr47)
                layout.add_widget(Wsr48)
                layout.add_widget(Wsr49)
                layout.add_widget(Wsr50)
                layout.add_widget(Button(background_normal='Letters/F.jpg', background_down='Letters/FC.jpg'))
                layout.add_widget(Wsr51)
                layout.add_widget(Wsr52)
                layout.add_widget(Wsr53)
                layout.add_widget(Wsr54)
                layout.add_widget(Wsr55)
                layout.add_widget(Wsr56)
                layout.add_widget(Wsr57)
                layout.add_widget(Wsr58)
                layout.add_widget(Wsr59)
                layout.add_widget(Wsr60)
                layout.add_widget(Button(background_normal='Letters/G.jpg', background_down='Letters/GC.jpg'))
                layout.add_widget(Wsr61)
                layout.add_widget(Wsr62)
                layout.add_widget(Wsr63)
                layout.add_widget(Wsr64)
                layout.add_widget(Wsr65)
                layout.add_widget(Wsr66)
                layout.add_widget(Wsr67)
                layout.add_widget(Wsr68)
                layout.add_widget(Wsr69)
                layout.add_widget(Wsr70)
                layout.add_widget(Button(background_normal='Letters/H.jpg', background_down='Letters/HC.jpg'))
                layout.add_widget(Wsr71)
                layout.add_widget(Wsr72)
                layout.add_widget(Wsr73)
                layout.add_widget(Wsr74)
                layout.add_widget(Wsr75)
                layout.add_widget(Wsr76)
                layout.add_widget(Wsr77)
                layout.add_widget(Wsr78)
                layout.add_widget(Wsr79)
                layout.add_widget(Wsr80)
                layout.add_widget(Button(background_normal='Letters/I.jpg', background_down='Letters/IC.jpg'))
                layout.add_widget(Wsr81)
                layout.add_widget(Wsr82)
                layout.add_widget(Wsr83)
                layout.add_widget(Wsr84)
                layout.add_widget(Wsr85)
                layout.add_widget(Wsr86)
                layout.add_widget(Wsr87)
                layout.add_widget(Wsr88)
                layout.add_widget(Wsr89)
                layout.add_widget(Wsr90)
                layout.add_widget(Button(background_normal='Letters/J.jpg', background_down='Letters/JC.jpg'))
                layout.add_widget(Wsr91)
                layout.add_widget(Wsr92)
                layout.add_widget(Wsr93)
                layout.add_widget(Wsr94)
                layout.add_widget(Wsr95)
                layout.add_widget(Wsr96)
                layout.add_widget(Wsr97)
                layout.add_widget(Wsr98)
                layout.add_widget(Wsr99)
                layout.add_widget(Wsr100)

                return layout


if __name__ == '__main__':
    Pitch().run()
